# Generated by Django 6.1.1 on 2026-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('published', 'Published'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('registered', 'Registered'), ('login', 'Login'), ('logout', 'Logout'), ('profile_updated', 'Profile Updated')], max_length=30),
        ),
    ]
